services:
  postgresql:
    from: postgres
  redis:
    from: redis:3.0.2
  rails:
    from: ruby:2.1.3
    cache:
      - /bundle
    build:
      - apt-get update
      - apt-get install -y libqt4-dev pkg-config
      - apt-get install -y curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev nodejs
      - apt-get install build-essential
      - gem install foreman

test:
  prepare:
    - bundle install
    - bin/rake db:create
  service: rails
  dependencies: [postgresql, redis]
  folder: /app
  cmd: bin/rspec
  env:
    - RAILS_ENV=test
    - RACK_ENV=test
    - DATABASE_URL=postgres://postgres:mysecretpassword@127.0.0.1:5432/db

staging:
  prepare:
    - bundle install
    - bin/rake db:create db:migrate db:seed
  service: rails
  dependencies: [postgresql, redis]
  folder: /app
  cmd: puma
  port: 80
  env:
    - RAILS_ENV=production
    - RACK_ENV=production
    - DATABASE_URL=postgres://postgres:mysecretpassword@127.0.0.1:5432/db
    - PORT=80
